# Generated by Django 4.2.14 on 2024-07-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('clicked_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Club',
            },
        ),
        migrations.CreateModel(
            name='ClubMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ClubMeeting',
                'verbose_name_plural': 'ClubMeeting',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('order', models.CharField(max_length=10)),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Step',
            },
        ),
        migrations.CreateModel(
            name='StepTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_for_each_test', models.FloatField()),
                ('question_type', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('type', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.step')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.TextField()),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('is_correct', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TestAnswer',
                'verbose_name_plural': 'TestAnswer',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='test')),
                ('steptest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.steptest')),
            ],
            options={
                'verbose_name': 'TestQuestion',
                'verbose_name_plural': 'TestQuestion',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.category')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancy',
            },
        ),
        migrations.CreateModel(
            name='UserTotalTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.FloatField()),
                ('step_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.steptest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'UserTotalTestResult',
                'verbose_name_plural': 'UserTotalTestResult',
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.testanswer')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.testquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'UserTestResult',
                'verbose_name_plural': 'UserTestResult',
            },
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_test_ball', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'UserSubject',
                'verbose_name_plural': 'UserSubject',
            },
        ),
        migrations.CreateModel(
            name='UserClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.club')),
                ('user', models.ManyToManyField(related_name='users', to='subject.club')),
            ],
            options={
                'verbose_name': 'UserClub',
                'verbose_name_plural': 'UserClub',
            },
        ),
        migrations.AddField(
            model_name='testanswer',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.testquestion'),
        ),
        migrations.CreateModel(
            name='SubjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.category')),
            ],
            options={
                'verbose_name': 'SubjectTitle',
                'verbose_name_plural': 'SubjectTitle',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjecttitle'),
        ),
        migrations.CreateModel(
            name='StepLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.step')),
            ],
            options={
                'verbose_name': 'StepLesson',
                'verbose_name_plural': 'StepLesson',
            },
        ),
        migrations.AddField(
            model_name='step',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='club',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
